### PR TITLE
bump MKL compat

### PR DESCRIPTION
**Pull request by KristofferC**

### CODE REVIEW

**Comment by KristofferC** [comment]
The issue in https://github.com/JuliaSparse/Pardiso.jl/issues/90 is now visible on CI. That's good.

**Comment by jd-lara** [comment]
@KristofferC can we merge this any time soon even if the apple version isn't working?

**Comment by jd-lara** [comment]
bump @KristofferC to merge this please

**Comment by jd-lara** [comment]
@KristofferC bump again to merge this PR and release.

**Pull request merged**
