### PR TITLE
added schur_complement, pardisogetschur, wrapper for pardiso_get_schur

### PR DESCRIPTION
**Pull request by wrs28**
Added ccall wrapper for pardiso_get_schur per #33, called `pardisogetschur`

Added a function for convenience as well: `schur_complement(ps,A,x)` where x can be `Int` or sparse vector or matrix. If `int` then Schur complement block defined to be last `x` rows and columns of `A`. If sparse vector or matrix, then populated rows of `x` define Schur complement variables.

### CODE REVIEW

**Comment by wrs28** [comment]
It's worth mentioning that this is only for Pardiso 5/6, not MKL.

**Comment by wrs28** [comment]
updated supported gfortran versions (added some forward compatibility too)

any chance someone can take a look at this, @KristofferC ?

**Comment by KristofferC** [comment]
Cool,

There need to be an entry about this in the README so people know about it and also some tests to see things are working ok.

**Comment by wrs28** [comment]
Added documentation in the readme, made the API for Schur complement mirror that of `solve`.

Interestingly, something about the computation seems to be unstable for complex numbers. I haven't been able to figure out where the issue is coming from, but I have ruled out the retrieval of the Schur complement through `pardisogetschur` as a source. Repeated calls to `pardiso` gives wildly different answers with huge exponents, perhaps it is related to some uninitialized memory?

For now I put a warning in the documentation to this effect, and leaving out tests for complex matrices for Schur complement.

Obviously this needs addressing, but for now it works reliably for the real (nonsymmetric) case.

**Comment by KristofferC** [comment]
Thanks for this and sorry for the terribly long wait time!

**Pull request merged**
