### PR TITLE
add back loading libgomp

### PR DESCRIPTION
**Pull request by KristofferC**
Can you try this @photicus?

### CODE REVIEW

**Comment by photicus** [comment]
Tests pass:
```julia
julia> Pkg.test("Pardiso")
INFO: Testing Pardiso
Testing DataType[Pardiso.MKLPardisoSolver]
Test Summary: | Pass  Total
solving       |   48     48
Test Summary: | Pass  Total
error checks  |    5      5
Test Summary:       | Pass  Total
getters and setters |    8      8
INFO: Pardiso tests passed
```

**Comment by KristofferC** [comment]
Lovely, let's get a new version out.

**Comment by KristofferC** [comment]
New version tagged, I think there is a bit of a CI queue for METADATA so might take a bit before it gets merged. Thanks again for the report. It is quite difficult to test these type of packages that wraps non-free software on multiple OS and MKL versions etc.

**Comment by photicus** [comment]
Thanks for the quick fix! And many thanks for this package too! It has saved me from trying to figure out how to load it up on my system, let alone multiple OSs and library versions.

**Pull request merged**
