### PR TITLE
Removing hard-coded MKL in tests

### PR DESCRIPTION
**Pull request by mipals**
This is a first try to make tests available for Panua-Pardiso when MKL is not installed as noted in #96 . Not all tests passes, however, as there is currently some issues with the err returned in Panua-Pardiso 7.2 and upwards (as discussed in #75 ).

In addition MKL_jll is pinned to 2023 in testing for macOS on intel machines.

The examples is also make into functions with either `MKLPardisoSolver` or `PardisoSolver` as inputs. Currently the functions just wraps the old code. This can definitely be made cleaner.

### CODE REVIEW

**Comment by mipals** [comment]
MKL_jll 2023 seem to work fine on macOS #96

**Comment by KristofferC** [comment]
Update README to say to use 2023 instead?

After that, LGTM.

**Comment by mipals** [comment]
So, should i merge?

**Comment by KristofferC** [comment]
👍  go for it

**Pull request merged**
